"""Curated reference set for the sentence-embedding k-NN method.

Each entry is (text, label) with label 1 = hateful/offensive, 0 = not.
The method embeds the input and votes based on its nearest neighbors here,
rather than a trained classifier — so this list *is* the "model".
"""

REFERENCE_EXAMPLES = [
    # English — hateful (1)
    ("You people are all disgusting and don't deserve to live here.", 1),
    ("Go back to where you came from, nobody wants you.", 1),
    ("You're such a worthless piece of trash, just disappear already.", 1),
    ("I hope something terrible happens to you and your whole family.", 1),
    ("Everyone like you is subhuman garbage that should be wiped out.", 1),
    ("Shut your ugly mouth before I shut it for you.", 1),
    ("You're too stupid to even exist, honestly pathetic.", 1),
    ("People from that country are all criminals and animals.", 1),
    ("Kill yourself, nobody would even notice.", 1),
    ("Women like you don't deserve respect, just shut up.", 1),
    ("I despise everything about your kind, you make me sick.", 1),
    ("You're a waste of oxygen and everyone agrees.", 1),
    ("Get lost, freak, no one wants you around here.", 1),
    ("Your entire religion is a disease that needs to be erased.", 1),
    ("You're an embarrassment to the human race.", 1),
    # English — not hateful (0)
    ("Thanks so much for helping me move this weekend!", 0),
    ("I really enjoyed the concert last night, great show.", 0),
    ("Could you send me the report before Friday, please?", 0),
    ("I disagree with your point, but I see where you're coming from.", 0),
    ("This restaurant has amazing food, you should try it.", 0),
    ("I'm a bit tired today, going to bed early.", 0),
    ("Congratulations on your new job, well deserved!", 0),
    ("The weather has been lovely this week.", 0),
    ("Let's grab coffee sometime and catch up.", 0),
    ("That movie was okay, not really my favorite genre.", 0),
    ("I'm frustrated with this bug but we'll figure it out.", 0),
    ("Happy birthday, hope you have a wonderful day!", 0),
    ("The traffic was terrible this morning, ugh.", 0),
    ("Great presentation today, really clear and well organized.", 0),
    ("I don't think that plan will work, let's reconsider it.", 0),
    # German — hateful (1)
    ("Ihr seid alle widerlich und gehört nicht hierher.", 1),
    ("Geh zurück in dein Land, hier will dich niemand.", 1),
    ("Du bist so ein wertloses Stück Dreck, verschwinde einfach.", 1),
    ("Ich hoffe deiner ganzen Familie passiert etwas Schreckliches.", 1),
    ("Leute wie du sind Untermenschen und gehören ausgerottet.", 1),
    ("Halt deine hässliche Fresse, bevor ich sie dir stopfe.", 1),
    ("Du bist zu dumm um überhaupt zu existieren, echt erbärmlich.", 1),
    ("Alle aus diesem Land sind Verbrecher und Tiere.", 1),
    ("Bring dich um, es würde sowieso niemand merken.", 1),
    ("Frauen wie du verdienen keinen Respekt, halt einfach die Klappe.", 1),
    ("Ich verabscheue alles an deiner Sorte, ihr macht mich krank.", 1),
    ("Du bist eine Verschwendung von Sauerstoff.", 1),
    ("Verpiss dich, Freak, hier will dich keiner haben.", 1),
    ("Deine ganze Religion ist eine Krankheit, die ausgelöscht gehört.", 1),
    ("Du bist eine Schande für die Menschheit.", 1),
    # German — not hateful (0)
    ("Danke, dass du mir beim Umzug geholfen hast!", 0),
    ("Das Konzert gestern Abend war wirklich toll.", 0),
    ("Kannst du mir den Bericht bis Freitag schicken?", 0),
    ("Ich sehe das anders, verstehe aber deinen Punkt.", 0),
    ("Das Restaurant hat großartiges Essen, probier es mal.", 0),
    ("Ich bin heute etwas müde, gehe früh ins Bett.", 0),
    ("Herzlichen Glückwunsch zum neuen Job, gut verdient!", 0),
    ("Das Wetter war diese Woche wirklich schön.", 0),
    ("Lass uns mal wieder einen Kaffee trinken gehen.", 0),
    ("Der Film war ganz okay, nicht so mein Genre.", 0),
    ("Ich bin von dem Bug genervt, aber wir kriegen das hin.", 0),
    ("Alles Gute zum Geburtstag, ich wünsche dir einen schönen Tag!", 0),
    ("Der Verkehr heute Morgen war furchtbar.", 0),
    ("Tolle Präsentation heute, wirklich klar und gut strukturiert.", 0),
    ("Ich glaube der Plan funktioniert nicht, lass uns umdenken.", 0),
]
